name: slow
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  provider: ^6.0.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.1.0
  flutter_svg: ^0.22.0
  reactive_forms: ^11.0.1
  dio: ^4.0.6
  retrofit: any
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.8
  modal_bottom_sheet: ^2.0.0
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  emoji_picker_flutter: ^1.5.1
  flutter_keyboard_visibility: ^5.0.0
  keyboard_visibility_pro: ^0.0.1
  flutter_persistent_keyboard_height: ^1.0.5
  file_picker: ^5.2.5
  better_open_file: ^3.6.4
  photo_view: ^0.14.0
  video_player: ^2.5.1
  audioplayers: ^2.0.0
  audio_waveforms: ^1.0.1
  bubble: ^1.2.1
  dropdown_button2: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.1.1
  retrofit_generator: any
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Generates files with given ignore rules for file.
  # ignored_rules:
  #   - public_member_api_docs
  # Generates dart font family references for fonts specified in pubspec.yaml
  # fonts: true
  # -------- OR --------
  # fonts:
  #   class_name: MyFonts
  #   file_name: my_fonts
  # Location where all the generated references will be stored
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
    - path: assets/icons
      class_name: Svgs
      types: [ .svg ]